--- #YAML:1.0
name:               Crypt-Passwd-XS
version:            0.504
abstract:           Full XS implementation of common crypt() algorythms
author:
    - John Lightsey <jd@cpanel.net>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0
resources:
    license:  http://dev.perl.org/licenses/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
